image: uber/android-build-environment:latest

pipelines:
  default:
    - step:
        script: 
            # Grab the Android Support Repo which isn't included in the container
          - echo y | android update sdk --all --no-ui --filter "build-tools-24.0.3, extra-android-support, extra-android-m2repository, extra-google-google_play_services, extra-google-m2repository"
          - pwd
          - ls ./
            # update submodules (libraries)
          - git clone https://yaroslav_havrylovych@bitbucket.org/yaroslav_havrylovych/andengine.git
          - ls ./andengine
          - git clone https://yaroslav_havrylovych@bitbucket.org/yaroslav_havrylovych/andenginephysicsbox2dextension.git
          - ls ./andenginephysicsbox2dextension
          - git clone https://yaroslav_havrylovych@bitbucket.org/yaroslav_havrylovych/andenginemultiplayerextension.git
          - ls ./andenginemultiplayerextension
            # copy android licenses
          - cp -r ./android_licenses /usr/local/android-sdk/licenses
            # Building a dev build variant
          - ./gradlew clean assembleDevDebug --stacktrace
