image: uber/android-build-environment:latest

pipelines:
  default:
    - step:
        script: 
            # Grab the Android Support Repo which isn't included in the container
          - echo y | android update sdk --filter "extra-android-m2repository" --no-ui -a
            # update submodules (libraries)
          - git clone https://yaroslav_havrylovych@bitbucket.org/yaroslav_havrylovych/andengine.git
          - git clone https://yaroslav_havrylovych@bitbucket.org/yaroslav_havrylovych/andenginephysicsbox2dextension.git
          - git clone https://yaroslav_havrylovych@bitbucket.org/yaroslav_havrylovych/andenginemultiplayerextension.git
            # copy android licenses
          - cp -r ./android_licenses /usr/local/android-sdk/licenses
            # Building a dev build variant
          - ./gradlew clean assembleDevDebug
